export default {
  ticker: "#fund-ticker",
  dividend_yield: "#informations--indexes > div:nth-child(1) > span.value",
  last_yield: "#informations--indexes > div:nth-child(2) > span.value",
  net_worth: "#informations--indexes > div:nth-child(3) > span.value",
  equity_value: "#informations--indexes > div:nth-child(4) > span.value",
  notes: "#informations--extra > div.notas > p",
  current: "#quotations--infos-wrapper > div.item.quotation > span.value",
  current_eval: "#quotations--infos-wrapper > div.item.quotation > div > span",
  eval_last12month: "#quotations--infos-wrapper > div.item-group > div.item.val12 > div.value > span:nth-child(1)",
  adm_name: "#informations--admin > div.top-content > div.text-wrapper > span.administrator-name",
  adm_cnpj: "#informations--admin > div.top-content > div.text-wrapper > span.administrator-doc",
  adm_phone: "#informations--admin > div.bottom-content > div:nth-child(1) > div.text-wrapper > span.value",
  adm_email: "#informations--admin > div.bottom-content > div:nth-child(2) > div.text-wrapper > span.value > a",
  adm_site: "#informations--admin > div.bottom-content > div:nth-child(3) > div.text-wrapper > span.value",
};
